package com.parabank.automation.enums;

public enum ContextKey {
	CUSTOMER_ID, UI_ACCOUNT_IDS, API_ACCOUNT_IDS, API_STATUS_CODE, COOKIE_HEADER, API_ACCOUNTS, PRE_UI_ACCOUNT_IDS,
	POST_UI_ACCOUNT_IDS, PRE_API_ACCOUNT_IDS, POST_API_ACCOUNT_IDS, NEW_ACCOUNT_ID
}